name: Count Katalon WebUI Keywords

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  count_keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install Groovy
      run: |
        sudo apt-get update
        sudo apt-get install -y groovy

    - name: Run the Groovy keyword counting script
      run: groovy Scripts/CountKeywords/Script1760369992141.groovy
